### ISSUE TITLE
issues building

### ISSUE THREAD

**Issue by mzimmers** [chrta/sip_call#14]
Hi -

I'm looking forward to getting this software to build. Currently, I'm attempting to build using esp-idf v4.1, and v8.2 of the toolchain. Target will be a proprietary board using the WROVER. 

I'm getting two build errors:

1. multiple definitions of if_indextoname(). This appears to be part of a workaround for an asio bug, but I wonder if the definition in lwip_udp_client.h may now be an anachronism.
2. undefined references to several routines that appear to be C++ error handling routines, eg. _Unwind_Resume.

Thanks for any assistance on this.

**Comment by chrta** [comment]
See also https://github.com/espressif/esp-idf/issues/4490 After upgrading to the current master and ensuring that you use a supported toolchain, you have to run:
```
idf.py fullclean
```

After that also your 2nd error should be gone. I have not tested this on hardware, yet.

**Comment by mzimmers** [comment]
Thank you Christian. I did a full clean on my project, and I believe my toolchain is supported:
![toolchain](https://user-images.githubusercontent.com/1409026/73779050-f90bca80-4740-11ea-976e-68c247b3ffad.PNG)
This eliminated the C++ error handler errors; I'm still getting the duplicate definition error, though.

**Comment by chrta** [comment]
> I'm still getting the duplicate definition error, though.

Have you pulled my latest change? It is working for me in linux.

**Comment by mzimmers** [comment]
You fixed this since yesterday? Anyway, yes, it builds now...thanks for the help. I'm sure I'll have more questions down the road.

**Comment by chrta** [comment]
Yes, see the linked commit above. Glad to hear that it works now.
